"""Public API for optical propagation sanity checks."""

from .checks import CHECK_NAMES, check_by_name, field_errors, sanity_check
from .grids import (
    centered_axes,
    fft2c,
    frequency_grid,
    gaussian_field,
    ifft2c,
    square_aperture,
)
from .plotting import render_status_matrix
from .propagators import (
    ASM_BANDLIMITED_PADDED_MODEL,
    ASM_MODEL,
    ASM_PADDED_MODEL,
    ASM_UNBANDED_MODEL,
    BLAS_MODEL,
    DIRECT_INTEGRATION_MODEL,
    FFT_DI_MODEL,
    FRAUNHOFER_MODEL,
    FRESNEL_MODEL,
    UNBANDED_ASM_MODEL,
    exact_asm_phase,
    fresnel_phase,
    propagate_asm,
    propagate_asm_padded,
    propagate_asm_unbandlimited,
    propagate_direct_integration,
    propagate_fft_di,
    propagate_fraunhofer,
    propagate_fresnel,
)
from .types import (
    CheckResult,
    GridSpec,
    PropagationModel,
    PropagationResult,
    PropagationSpec,
    SanityReport,
    SanityThresholds,
)

__all__ = [
    "ASM_BANDLIMITED_PADDED_MODEL",
    "ASM_MODEL",
    "ASM_PADDED_MODEL",
    "ASM_UNBANDED_MODEL",
    "BLAS_MODEL",
    "CHECK_NAMES",
    "CheckResult",
    "DIRECT_INTEGRATION_MODEL",
    "FFT_DI_MODEL",
    "FRAUNHOFER_MODEL",
    "FRESNEL_MODEL",
    "GridSpec",
    "PropagationModel",
    "PropagationResult",
    "PropagationSpec",
    "SanityReport",
    "SanityThresholds",
    "UNBANDED_ASM_MODEL",
    "centered_axes",
    "check_by_name",
    "exact_asm_phase",
    "fft2c",
    "field_errors",
    "frequency_grid",
    "fresnel_phase",
    "gaussian_field",
    "ifft2c",
    "propagate_asm",
    "propagate_asm_padded",
    "propagate_asm_unbandlimited",
    "propagate_direct_integration",
    "propagate_fft_di",
    "propagate_fraunhofer",
    "propagate_fresnel",
    "render_status_matrix",
    "sanity_check",
    "square_aperture",
]
